# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(help_text='Escribir nombre del pa\xeds.', max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('descripcion', models.TextField(blank=True, help_text='Escribe una descripci\xf3n del pais.')),
            ],
        ),
    ]
