# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos_identificaciones', '0001_initial'),
        ('estados_civiles', '0001_initial'),
        ('zonas', '0001_initial'),
        ('grupos_sanguineos', '0001_initial'),
        ('distritos', '0002_auto_20160115_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir nombre(s).', max_length=255)),
                ('apellido_paterno', models.CharField(help_text='Escribir apellido paterno.', max_length=255)),
                ('apellido_materno', models.CharField(help_text='Escribir apellido materno.', max_length=255)),
                ('numero_documento_identificacion', models.CharField(help_text='Escribir n\xfamero documento identificaci\xf3n', max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.BooleanField(choices=[(True, 'Masculino'), (False, 'Femenino')])),
                ('fotografia', models.ImageField(blank=True, upload_to='fotograf\xeda')),
                ('observacion_persona', models.TextField(blank=True, help_text='Escribir observaci\xf3n de la persona (Opcional).')),
                ('nombre_direccion', models.CharField(blank=True, help_text='Escribir direcci\xf3n.', max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=20)),
                ('piso', models.CharField(blank=True, max_length=20)),
                ('interior', models.CharField(blank=True, max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('cuadra', models.CharField(blank=True, max_length=20)),
                ('manzana', models.CharField(blank=True, max_length=20)),
                ('lote', models.CharField(blank=True, max_length=20)),
                ('sub_lote', models.CharField(blank=True, max_length=20)),
                ('denominacion', models.CharField(blank=True, help_text='Escribir denominaci\xf3n (Opcional).', max_length=255)),
                ('referencia', models.CharField(blank=True, help_text='Escribir referencia (Opcional).', max_length=255)),
                ('observacion_direccion', models.CharField(blank=True, help_text='Escribir observaci\xf3n de la direcci\xf3n (Opcional).', max_length=255)),
                ('telefono_personal', models.CharField(blank=True, max_length=20)),
                ('celular_personal', models.CharField(blank=True, max_length=20)),
                ('e_mail', models.EmailField(blank=True, max_length=255)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distritos.Distrito')),
                ('documento_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos_identificaciones.DocumentoIdentificacion')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados_civiles.EstadoCivil')),
                ('grupo_sanguineo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos_sanguineos.GrupoSanguineo')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.Zona')),
            ],
        ),
    ]
